EBC\PublisherClient\Campaign\Campaign:
    properties:
        id:
            type: integer
        name:
            type: string
        advertiser:
            type: EBC\PublisherClient\Advertiser\Advertiser
        country:
            type: EBC\PublisherClient\Locale\Country
        schedule:
            type: EBC\PublisherClient\Campaign\Schedule
        totalPayout:
            type: EBC\PublisherClient\Campaign\Payout
        publisherPayout:
            type: EBC\PublisherClient\Campaign\Payout
        listsApproval:
            type: EBC\PublisherClient\Campaign\ListsApproval
        categories:
            type: EBC\PublisherClient\Campaign\Categories
        updatedAt:
            type: EBT\EBDate\EBDateTime
