EBC\PublisherClient\Campaign\Campaign:
    properties:
        id:
            type: integer
        name:
            type: string
        description:
            type: string
        country:
            type: EBC\PublisherClient\Locale\Country
        schedule:
            type: EBC\PublisherClient\Campaign\Schedule
        payout:
            type: EBC\PublisherClient\Campaign\Payout
        listsApproval:
            type: EBC\PublisherClient\Campaign\ListsApproval
        categories:
            type: EBC\PublisherClient\Campaign\Categories
        announcer:
            type: EBC\PublisherClient\Campaign\Announcer
        updatedAt:
            type: EBT\EBDate\EBDateTime
        isProvenienceWhitelabel:
            type: boolean
        isPaused:
            type: boolean
