EBC\PublisherClient\PublisherList\PublisherList:
    properties:
        id:
            type: string
        name:
            type: string
        description:
            type: string
        interests:
            type: EBC\PublisherClient\PublisherList\Interests
        fromName:
            type: string
        fromEmail:
            type: string
        publicName:
            type: string
        customDomain:
            type: string
        headDomain:
            type: string
        trackingDomain:
            type: string
        replyToEmail:
            type: string
        defaultCountryName:
            type: string
        listTemplateId:
            type: integer
        approvalRulesId:
            type: integer
        approvalRulesName:
            type: string
        approvedCategories:
            type: array
        minPayoutParentCategories:
            type: array
        minPayoutChildCategories:
            type: array
