name: Publisher Client
baseUrl: "{scheme}://{host}{+basePath}/{publisherId}"
description: Publisher Client
operations:
    getCampaign:
        httpMethod: GET
        uri: campaigns/{campaignId}
        responseClass: 'EBC\PublisherClient\Campaign\Campaign'
        summary: Returns one campaign
        data:
            acceptedStatusCodes: 200
        parameters:
            campaignId:
                location: uri
                description: Id of the campaign to use
                type: integer
                required: true
            accept:
                location: 'header'
                default: 'application/vnd.emailbidding+json; version=1.2.2'

    getCampaignCreativities:
        httpMethod: GET
        uri: campaigns/{campaignId}/creativities
        responseClass: 'EBC\PublisherClient\Campaign\Creativities'
        summary: Returns the creativity for one campaign
        data:
            acceptedStatusCodes: 200
        parameters:
            campaignId:
                location: uri
                description: Id of the campaign to use
                type: integer
                required: true

    getCampaigns:
        httpMethod: GET
        uri: campaigns
        responseClass: 'EBC\PublisherClient\Campaign\Campaigns'
        summary: Returns campaigns that publisher have access
        data:
            acceptedStatusCodes: 200
        parameters:
            orderBy:
                location: query
                description: How to order the result set (created|updated)
                type: string
                minLength: 2
                maxLength: 64
                required: false
                sentAs: order_by
            order:
                location: query
                description: Order asc|desc|ASC|DESC
                type: string
                minLength: 3
                maxLength: 4
                required: false
            endDateGreaterThan:
                location: query
                description: End date for campaign greater than (YYYY-MM-DD)
                type: string
                minLength: 10
                maxLength: 10
                required: false
            country:
                location: query
                description: Campaigns' country
                type: integer
                required: false
            category:
                location: query
                description: Campaigns' category
                type: integer
                required: false
            limit:
                location: query
                description: Number of campaigns to get
                type: integer
                required: false
            accept:
                location: 'header'
                default: 'application/vnd.emailbidding+json; version=1.2.2'
    getCampaignListApproval:
        httpMethod: GET
        uri: campaigns/{campaignId}/lists/{listId}
        responseClass: 'EBC\PublisherClient\Campaign\Approval'
        summary: Returns approval of a campaign for a list
        data:
            acceptedStatusCodes: 200
        parameters:
            campaignId:
                location: uri
                description: id of the campaign
                type: integer
                required: true
            listId:
                location: uri
                description: id of the list
                type: string
                required: true
            accept:
                location: 'header'
                default: 'application/vnd.emailbidding+json; version=1.2.2'
    getLists:
        httpMethod: GET
        uri: lists
        responseClass: 'EBC\PublisherClient\PublisherList\PublisherLists'
        summary: Returns publisher lists
        data:
            acceptedStatusCodes: 200
        parameters:
            accept:
                location: 'header'
                default: 'application/vnd.emailbidding+json; version=1.2.0'
    getListById:
        httpMethod: GET
        uri: lists/{id}
        responseClass: 'EBC\PublisherClient\PublisherList\PublisherList'
        summary: Returns a list of a publisher by its id
        data:
            acceptedStatusCodes: 200
        parameters:
            id:
                location: uri
                description: id of the list to get
                type: string
                required: true
            accept:
                location: 'header'
                default: 'application/vnd.emailbidding+json; version=1.2.0'
    updateListById:
        httpMethod: PATCH
        uri: lists/{id}
        summary: Returns a list of a publisher by its id
        data:
            acceptedStatusCodes: 204
        parameters:
            id:
                location: uri
                description: id of the list to set
                type: string
                required: true
            list_definition_update:
                location: json
                description: The form for list definition
                type: object
                required: true
                properties:
                    id:
                        location: json
                        type: string
                        required: true
                    name:
                        location: json
                        required: false
                        type: string
                    description:
                        location: json
                        required: false
                        type: string
                    fromName:
                        location: json
                        required: false
                        type: string
                    publicName:
                        location: json
                        required: false
                        type: string
                    listTemplateId:
                        location: json
                        required: false
                        type: integer
                    approvalRulesId:
                        location: json
                        required: false
                        type: integer
                    approvedCategories:
                        location: json
                        required: false
                        type: array
                    minPayoutParentCategories:
                        location: json
                        required: false
                        type: string
                    minPayoutChildCategories:
                        location: json
                        required: false
                        type: string
                    isEnabledForCPMBidding:
                        location: json
                        required: false
                        type: boolean
            accept:
                location: 'header'
                default: 'application/vnd.emailbidding+json; version=1.2.0'
    getListsApprovalExceptions:
        httpMethod: GET
        uri: lists/approvals
        responseClass: 'EBC\PublisherClient\ListApprovalExceptions\ListsApprovalExceptions'
        summary: Returns publisher lists
        data:
            acceptedStatusCodes: 200
        parameters:
            accept:
                location: 'header'
                default: 'application/vnd.emailbidding+json; version=1.2.0'
    getListApprovalExceptionsById:
        httpMethod: GET
        uri: lists/{id}/approvals
        responseClass: 'EBC\PublisherClient\ListApprovalExceptions\ListApprovalExceptions'
        summary: Returns a list of a publisher by its id
        data:
            acceptedStatusCodes: 200
        parameters:
            id:
                location: uri
                description: id of the list to get
                type: string
                required: true
            accept:
                location: 'header'
                default: 'application/vnd.emailbidding+json; version=1.2.0'
    updateListApprovalExceptions:
        httpMethod: PATCH
        uri: lists/{id}/approvals
        summary: Update a list by a publisher
        data:
            acceptedStatusCodes: 204
        parameters:
            id:
                location: uri
                description: The list Id
                type: string
                minLength: 1
                required: true
            list_approval_exceptions_update:
                location: json
                description: The form approval exceptions
                type: object
                required: true
                properties:
                    approved:
                        location: json
                        required: false
                        type: array
                    rejected:
                        location: json
                        required: false
                        type: array
            accept:
                location: 'header'
                default: 'application/vnd.emailbidding+json; version=1.2.0'
    getListStats:
        httpMethod: GET
        uri: lists/stats
        responseClass: 'EBC\PublisherClient\PublisherList\PublisherListsStats'
        summary: Returns publisher lists stats (totals)
        data:
            acceptedStatusCodes: 200
        parameters:
            accept:
                location: 'header'
                default: 'application/vnd.emailbidding+json; version=1.2.0'
