name: Publisher Client
baseUrl: "{scheme}://{host}{+basePath}/{publisherId}"
description: Publisher Client
operations:
    getCampaigns:
        httpMethod: GET
        uri: campaigns
        responseClass: 'EBC\PublisherClient\Campaign\Campaigns'
        summary: Returns campaigns that publisher have access
        data:
            acceptedStatusCodes: 200
        parameters:
            orderBy:
                location: query
                description: How to order the result set (created|updated)
                type: string
                minLength: 2
                maxLength: 64
                required: false
                sentAs: order_by
            order:
                location: query
                description: Order asc|desc|ASC|DESC
                type: string
                minLength: 3
                maxLength: 4
                required: false
            endDateGreaterThan:
                location: query
                description: End date for campaign greater than (YYYY-MM-DD)
                type: string
                minLength: 10
                maxLength: 10
                required: false
            country:
                location: query
                description: Campaigns' country
                type: integer
                required: false
            category:
                location: query
                description: Campaigns' category
                type: integer
                required: false
    getLists:
        httpMethod: GET
        uri: lists
        responseClass: 'EBC\PublisherClient\ListDefinition\ListsDefinition'
        summary: Returns publisher lists
        data:
            acceptedStatusCodes: 200
